const fs = require('fs');
const f = 'c:/Users/ADMIN/Downloads/medailockr--simple-secure-smarter-healthcare-version-5.00/flutter_mediqly/lib/screens/health_twin/health_twin_screen.dart';
let c = fs.readFileSync(f, 'utf8');

// Check it hasn't already been added
if (c.includes('_VoiceAssistantSheet')) {
  console.log('Already added - skipping');
  process.exit(0);
}

const R = '\r\n';
const widget = R + [
  '// ─────────────────────────────────────────────────────────────────────────',
  '//  Voice Assistant Bottom Sheet',
  '// ─────────────────────────────────────────────────────────────────────────',
  'class _VoiceAssistantSheet extends StatefulWidget {',
  '  final String vitalsContext;',
  '  const _VoiceAssistantSheet({required this.vitalsContext});',
  '  @override',
  '  State<_VoiceAssistantSheet> createState() => _VoiceAssistantSheetState();',
  '}',
  '',
  'class _VoiceAssistantSheetState extends State<_VoiceAssistantSheet> {',
  '  final _speech = stt.SpeechToText();',
  '  bool _listening = false;',
  '  bool _speechAvailable = false;',
  '  String _transcript = \'\';',
  '  String _response = \'\';',
  '  bool _thinking = false;',
  '  final List<Map<String, String>> _history = [];',
  '',
  '  @override',
  '  void initState() {',
  '    super.initState();',
  '    _initSpeech();',
  '  }',
  '',
  '  Future<void> _initSpeech() async {',
  '    final ok = await _speech.initialize();',
  '    if (mounted) setState(() => _speechAvailable = ok);',
  '  }',
  '',
  '  Future<void> _toggleListen() async {',
  '    if (_listening) {',
  '      await _speech.stop();',
  '      setState(() => _listening = false);',
  '      if (_transcript.isNotEmpty) _ask(_transcript);',
  '    } else {',
  "      setState(() { _listening = true; _transcript = ''; });",
  '      await _speech.listen(',
  "        onResult: (r) => setState(() => _transcript = r.recognizedWords),",
  "        listenFor: const Duration(seconds: 15),",
  "        pauseFor: const Duration(seconds: 3),",
  "        listenOptions: stt.SpeechListenOptions(partialResults: true),",
  '      );',
  '    }',
  '  }',
  '',
  '  Future<void> _ask(String text) async {',
  '    if (text.trim().isEmpty) return;',
  "    setState(() { _thinking = true; _response = ''; });",
  '    _history.add({\'role\': \'user\', \'text\': text});',
  '    try {',
  '      final prompt =',
  "          'Patient vitals: ${widget.vitalsContext}. '",
  "          'Answer the following health question concisely: $text';",
  '      final reply = await GeminiService.instance.chatSymptom(_history, prompt);',
  '      _history.add({\'role\': \'model\', \'text\': reply});',
  '      if (mounted) setState(() { _response = reply; _thinking = false; });',
  '    } catch (e) {',
  '      if (mounted) setState(() {',
  "        _response = 'Sorry, I could not get a response. Please try again.';",
  '        _thinking = false;',
  '      });',
  '    }',
  '  }',
  '',
  '  @override',
  '  void dispose() {',
  '    _speech.cancel();',
  '    super.dispose();',
  '  }',
  '',
  '  @override',
  '  Widget build(BuildContext context) {',
  '    return DraggableScrollableSheet(',
  '      initialChildSize: 0.65,',
  '      minChildSize: 0.4,',
  '      maxChildSize: 0.9,',
  '      expand: false,',
  '      builder: (ctx, sc) => Container(',
  '        decoration: const BoxDecoration(',
  '          color: _slate900,',
  '          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),',
  '        ),',
  '        child: Column(',
  '          children: [',
  '            // drag handle',
  '            Container(',
  '              margin: const EdgeInsets.only(top: 10, bottom: 6),',
  '              width: 36,',
  '              height: 4,',
  '              decoration: BoxDecoration(',
  '                color: _slate700,',
  '                borderRadius: BorderRadius.circular(2),',
  '              ),',
  '            ),',
  '            // header',
  '            Padding(',
  '              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),',
  '              child: Row(children: [',
  '                Container(',
  '                  padding: const EdgeInsets.all(8),',
  '                  decoration: BoxDecoration(',
  '                    color: _blue500.withValues(alpha: 0.15),',
  '                    borderRadius: BorderRadius.circular(10),',
  '                  ),',
  '                  child: const Icon(Icons.mic, color: _blue500, size: 18),',
  '                ),',
  '                const SizedBox(width: 10),',
  '                const Column(',
  '                  crossAxisAlignment: CrossAxisAlignment.start,',
  '                  children: [',
  "                    Text('MediQ Voice Assistant',",
  '                        style: TextStyle(',
  '                            color: Colors.white,',
  '                            fontWeight: FontWeight.w700,',
  '                            fontSize: 15)),',
  "                    Text('Ask about your vitals or symptoms',",
  '                        style: TextStyle(color: _slate400, fontSize: 11)),',
  '                  ],',
  '                ),',
  '                const Spacer(),',
  '                IconButton(',
  '                  onPressed: () => Navigator.pop(ctx),',
  '                  icon: const Icon(Icons.close, color: _slate400, size: 18),',
  '                ),',
  '              ]),',
  '            ),',
  '            const Divider(color: _slate800, height: 1),',
  '            // chat area',
  '            Expanded(',
  '              child: ListView(',
  '                controller: sc,',
  '                padding: const EdgeInsets.all(20),',
  '                children: [',
  '                  if (_transcript.isNotEmpty)',
  '                    _bubble(_transcript, isUser: true),',
  '                  if (_thinking)',
  '                    const Padding(',
  '                      padding: EdgeInsets.only(top: 12),',
  '                      child: Row(children: [',
  '                        SizedBox(',
  '                          width: 16, height: 16,',
  '                          child: CircularProgressIndicator(',
  '                            strokeWidth: 2, color: _blue500),',
  '                        ),',
  '                        SizedBox(width: 8),',
  "                        Text('Thinking...', style: TextStyle(color: _slate400, fontSize: 13)),",
  '                      ]),',
  '                    ),',
  '                  if (_response.isNotEmpty)',
  '                    _bubble(_response, isUser: false),',
  '                  if (!_speechAvailable && _transcript.isEmpty && _response.isEmpty)',
  '                    const Center(',
  '                      child: Padding(',
  '                        padding: EdgeInsets.only(top: 40),',
  "                        child: Text('Microphone not available.\nType your question below.',",
  '                            textAlign: TextAlign.center,',
  '                            style: TextStyle(color: _slate500, fontSize: 13)),',
  '                      ),',
  '                    ),',
  '                ],',
  '              ),',
  '            ),',
  '            // input row',
  '            Padding(',
  '              padding: EdgeInsets.only(',
  '                left: 16, right: 16, bottom: MediaQuery.of(context).viewInsets.bottom + 16, top: 8),',
  '              child: Row(children: [',
  '                // mic button',
  '                GestureDetector(',
  '                  onTap: _speechAvailable ? _toggleListen : null,',
  '                  child: AnimatedContainer(',
  '                    duration: const Duration(milliseconds: 200),',
  '                    width: 52, height: 52,',
  '                    decoration: BoxDecoration(',
  '                      shape: BoxShape.circle,',
  '                      color: _listening',
  '                          ? _blue500',
  '                          : _blue500.withValues(alpha: 0.15),',
  '                      border: _listening',
  '                          ? Border.all(color: _blue500, width: 2)',
  '                          : null,',
  '                    ),',
  '                    child: Icon(',
  '                      _listening ? Icons.stop : Icons.mic,',
  '                      color: _listening ? Colors.white : _blue500,',
  '                      size: 22,',
  '                    ),',
  '                  ),',
  '                ),',
  '                const SizedBox(width: 10),',
  '                // text field fallback',
  '                Expanded(',
  '                  child: _QuickTypeField(',
  '                    onSend: (text) {',
  '                      setState(() => _transcript = text);',
  '                      _ask(text);',
  '                    },',
  '                  ),',
  '                ),',
  '              ]),',
  '            ),',
  '          ],',
  '        ),',
  '      ),',
  '    );',
  '  }',
  '',
  '  Widget _bubble(String text, {required bool isUser}) {',
  '    return Align(',
  '      alignment: isUser ? Alignment.centerRight : Alignment.centerLeft,',
  '      child: Container(',
  '        margin: const EdgeInsets.only(bottom: 12),',
  '        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),',
  '        constraints: BoxConstraints(',
  '            maxWidth: MediaQuery.of(context).size.width * 0.75),',
  '        decoration: BoxDecoration(',
  '          color: isUser ? _blue500 : _slate800,',
  '          borderRadius: BorderRadius.circular(14),',
  '        ),',
  '        child: Text(text,',
  '            style: TextStyle(',
  '                color: isUser ? Colors.white : _slate200,',
  '                fontSize: 13)),',
  '      ),',
  '    );',
  '  }',
  '}',
  '',
  '// ─────────────────────────────────────────────────────────────────────────',
  '//  Quick-type text field for voice assistant',
  '// ─────────────────────────────────────────────────────────────────────────',
  'class _QuickTypeField extends StatefulWidget {',
  '  final ValueChanged<String> onSend;',
  '  const _QuickTypeField({required this.onSend});',
  '  @override',
  '  State<_QuickTypeField> createState() => _QuickTypeFieldState();',
  '}',
  '',
  'class _QuickTypeFieldState extends State<_QuickTypeField> {',
  '  final _ctrl = TextEditingController();',
  '',
  '  @override',
  '  void dispose() { _ctrl.dispose(); super.dispose(); }',
  '',
  '  @override',
  '  Widget build(BuildContext context) {',
  '    return TextField(',
  '      controller: _ctrl,',
  '      style: const TextStyle(color: Colors.white, fontSize: 13),',
  '      decoration: InputDecoration(',
  "        hintText: 'Type a question...',",
  '        hintStyle: const TextStyle(color: _slate500, fontSize: 13),',
  '        filled: true,',
  '        fillColor: _slate800,',
  '        contentPadding:',
  '            const EdgeInsets.symmetric(horizontal: 14, vertical: 10),',
  '        border: OutlineInputBorder(',
  '            borderRadius: BorderRadius.circular(26),',
  '            borderSide: BorderSide.none),',
  '        suffixIcon: IconButton(',
  '          icon: const Icon(Icons.send_rounded, color: _blue500, size: 18),',
  '          onPressed: () {',
  '            final t = _ctrl.text.trim();',
  '            if (t.isNotEmpty) { _ctrl.clear(); widget.onSend(t); }',
  '          },',
  '        ),',
  '      ),',
  '      onSubmitted: (t) {',
  '        if (t.trim().isNotEmpty) { _ctrl.clear(); widget.onSend(t.trim()); }',
  '      },',
  '    );',
  '  }',
  '}',
  '',
].join(R);

// Append before final closing blank lines
c = c.trimEnd() + R + widget;

fs.writeFileSync(f, c, 'utf8');
console.log('VoiceAssistantSheet appended. Final size:', c.length);
