/**
 * Pure-JS JSON file database — no native dependencies.
 * Each collection is a JSON array stored in /data/<collection>.json
 * Reads are served from an in-memory cache; writes flush to disk immediately.
 *
 * PRODUCTION NOTE: DynamoDB production layer is in db/dynamo-db.js.
 * Run  node db/dynamo-setup.js --seed  to provision AWS tables, then
 * update routes to import from '../db/dynamo-db' instead of '../db/database'.
 */
const fs   = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '../data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

// ── Collection ────────────────────────────────────────────────────────────────

class Collection {
  constructor(name) {
    this.name = name;
    this.file = path.join(DATA_DIR, `${name}.json`);
    this._data = [];
    this._load();
  }

  _load() {
    try {
      const raw = fs.readFileSync(this.file, 'utf8');
      this._data = JSON.parse(raw);
    } catch {
      this._data = [];
    }
  }

  _save() {
    fs.writeFileSync(this.file, JSON.stringify(this._data, null, 2), 'utf8');
  }

  insert(doc) {
    this._data.push(doc);
    this._save();
    return doc;
  }

  insertMany(docs) {
    this._data.push(...docs);
    this._save();
    return docs;
  }

  find(filter = {}, { sort = 'recorded_at', order = 'desc', limit = 1000, offset = 0 } = {}) {
    let result = this._data.filter(row => {
      for (const [k, v] of Object.entries(filter)) {
        if (typeof v === 'object' && v !== null) {
          if (v._gte !== undefined && row[k] < v._gte) return false;
          if (v._lte !== undefined && row[k] > v._lte) return false;
          if (v._ne  !== undefined && row[k] === v._ne)  return false;
        } else {
          if (row[k] !== v) return false;
        }
      }
      return true;
    });
    const field = sort || 'recorded_at';
    result.sort((a, b) => {
      const av = a[field] ?? '';
      const bv = b[field] ?? '';
      return order === 'asc' ? (av < bv ? -1 : 1) : (av > bv ? -1 : 1);
    });
    return result.slice(offset, offset + limit);
  }

  findOne(filter = {}) { return this.find(filter, { limit: 1 })[0] ?? null; }

  updateOne(filter, patch) {
    const idx = this._data.findIndex(row => Object.entries(filter).every(([k,v]) => row[k] === v));
    if (idx === -1) return null;
    this._data[idx] = { ...this._data[idx], ...patch };
    this._save();
    return this._data[idx];
  }

  updateMany(filter, patch) {
    let count = 0;
    this._data = this._data.map(row => {
      if (!Object.entries(filter).every(([k,v]) => row[k] === v)) return row;
      count++;
      return { ...row, ...patch };
    });
    if (count) this._save();
    return count;
  }

  count(filter = {}) { return this.find(filter, { limit: Number.MAX_SAFE_INTEGER }).length; }

  remove(filter = {}) {
    const before = this._data.length;
    this._data = this._data.filter(row => !Object.entries(filter).every(([k, v]) => row[k] === v));
    if (this._data.length !== before) this._save();
    return before - this._data.length;
  }
}

// ── Collections ───────────────────────────────────────────────────────────────
const vitals    = new Collection('vitals');
const insights  = new Collection('insights');
const alerts    = new Collection('alerts');
const ingestion       = new Collection('ingestion');
const profileColl     = new Collection('profile');
const events          = new Collection('events');
const medicosPosts    = new Collection('medicos_posts');
const medicosComments = new Collection('medicos_comments');

if (!profileColl.findOne({ id: 'default' })) {
  profileColl.insert({ id: 'default', name: 'Subject 01', age: null, gender: null, weight_kg: null, height_cm: null, blood_type: null, conditions: [], medications: [], created_at: new Date().toISOString(), updated_at: new Date().toISOString() });
}

// ── Seed Medicos posts & comments (Kaggle-inspired realistic medical community data) ──
const SEED_VERSION = 'v3-kaggle-2026';
const _seedMeta = path.join(DATA_DIR, '.medicos_seed_version');
const _currentSeedVer = (() => { try { return fs.readFileSync(_seedMeta, 'utf8').trim(); } catch { return ''; } })();

if (_currentSeedVer !== SEED_VERSION) {
  medicosPosts._data = [];
  medicosComments._data = [];

  const now = new Date();
  const ago = (h) => new Date(now.getTime() - h * 3600000).toISOString();

  const POSTS = [
    { id:'mp-001', author:{ name:'Dr. Arjun Nair',         title:'Interventional Cardiologist, AIIMS Delhi',          image:'https://i.pravatar.cc/150?img=11', verified:true  }, title:'STEMI in a 34-year-old runner: Spontaneous Coronary Artery Dissection (SCAD)?',                                    body:"35F, marathon runner, no traditional CV risk factors. Troponin I peaked 18 ng/mL. Coronary angio revealed Type 2 SCAD in LAD — managed conservatively. SCAD accounts for ~25% of MI in women <50 yet remains grossly underdiagnosed. Key teaching: always consider SCAD in young athletic women. What's your institutional approach to anti-platelet therapy duration in SCAD?",                                                                                                                         imageUrl:null, tags:['#Cardiology','#SCAD','#CaseStudy','#WomensHealth'],             specialty:'Cardiology',         flair:'Case Study',          upvotes:312, downvotes:8,  comments:5, shares:38, awards:[{type:'insightful',count:5},{type:'gold',count:1}],                            is_pinned:true,  created_at:ago(22),  updated_at:ago(22)  },
    { id:'mp-002', author:{ name:'Dr. Priya Mehta',         title:'Pediatric Surgeon, KEM Hospital Mumbai',            image:'https://i.pravatar.cc/150?img=54', verified:true  }, title:'ERAS Protocol for Pediatric Colorectal Surgery — 12-Month Outcomes',                                               body:'After implementing ERAS in our paediatric colorectal unit: mean LOS dropped 8.2→5.6 days, opioid use reduced 41%, readmission rate unchanged at 3.2%. Early enteral feeding (Day 0 post-op) and targeted fluid therapy gave the biggest wins. Key challenge: parental anxiety around early discharge — family education was critical. Anyone running ERAS in paediatric HPB?',                                                                                                                          imageUrl:null, tags:['#Pediatrics','#ERAS','#Perioperative','#QualityImprovement'],  specialty:'Pediatrics',         flair:'Protocol',            upvotes:278, downvotes:11, comments:5, shares:52, awards:[{type:'helpful',count:6},{type:'insightful',count:3}],                        is_pinned:false, created_at:ago(34),  updated_at:ago(34)  },
    { id:'mp-003', author:{ name:'Dr. Rajesh Kumar',        title:'Senior Neurologist, Bombay Hospital',               image:'https://i.pravatar.cc/150?img=58', verified:true  }, title:"Lecanemab vs Donanemab in Early Alzheimer's — Real-World Thoughts?",                                              body:"Both lecanemab and donanemab have shown statistically significant slowing of decline in Phase 3. But NNTs remain large and ARIA rates are concerning. The amyloid PET prerequisite alone is a massive access barrier in India — costs \u20B92.4L+ and is not covered. What are practitioners doing on the ground? Biomarker stratification? CSF? Plasma p-tau217 screening?",                                                                                                                        imageUrl:null, tags:['#Neurology','#Alzheimers','#Immunotherapy','#Research'],        specialty:'Neurology',          flair:'Research',            upvotes:421, downvotes:16, comments:5, shares:89, awards:[{type:'gold',count:2},{type:'helpful',count:7},{type:'insightful',count:4}],  is_pinned:false, created_at:ago(49),  updated_at:ago(49)  },
    { id:'mp-004', author:{ name:'Dr. Sneha Patel',         title:'Dermatologist & Skin Cancer Specialist',            image:'https://i.pravatar.cc/150?img=47', verified:true  }, title:'Rapidly Enlarging Nodule on Scalp — Merkel Cell or SCC?',                                                          body:'72M immunosuppressed (renal Tx), 2.8 cm firm violaceous nodule on vertex scalp growing over 6 weeks. Clinically the firmness and rapid growth worry me for Merkel Cell Carcinoma. CK20+/TTF-1\u2212 pattern on IHC would confirm. Anyone using 68Ga-DOTATATE PET for MCC staging? Immunotherapy (avelumab vs pembrolizumab) in transplant patients — rejection risk?',                                                                                                                  imageUrl:null, tags:['#Dermatology','#MerkelCell','#SkinCancer','#Immunosuppression'], specialty:'Dermatology',        flair:'Case Study',          upvotes:183, downvotes:6,  comments:4, shares:27, awards:[{type:'helpful',count:4},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(27),  updated_at:ago(27)  },
    { id:'mp-005', author:{ name:'Dr. Vikram Sinha',        title:'Consultant Orthopaedic Surgeon',                    image:'https://i.pravatar.cc/150?img=60', verified:true  }, title:'Robotic-Assisted TKA vs Conventional — Is the Learning Curve Worth It?',                                          body:'After 200 robotic TKAs (MAKO system): OR time added ~22 min early, now ~8 min extra at 200 cases. Radiographic outlier rate 11%\u21922.3%. OKS at 12m marginally better. Cost per case increased ~$2,100. Honest take: excellent for complex deformity and training programmes, but for routine primary TKA the benefit is real but incremental.',                                                                                                                                         imageUrl:null, tags:['#Orthopedics','#TKA','#RoboticSurgery','#MAKO'],              specialty:'Orthopedics',        flair:'Discussion',          upvotes:247, downvotes:22, comments:4, shares:44, awards:[{type:'insightful',count:5},{type:'helpful',count:3}],                        is_pinned:false, created_at:ago(63),  updated_at:ago(63)  },
    { id:'mp-006', author:{ name:'Dr. Fatima Malik',        title:'Ophthalmologist, LV Prasad Eye Institute',          image:'https://i.pravatar.cc/150?img=48', verified:true  }, title:'Bilateral Uveitis + Hilar Lymphadenopathy — Sarcoid or TB?',                                                      body:'34M bilateral anterior uveitis, bilateral hilar lymphadenopathy on CT, elevated serum ACE 68 U/L, arthralgia. Mantoux negative, IGRA pending. Differential: sarcoidosis vs TB. In India the TB prior probability is substantially higher even with this classic sarcoid picture. At what ACE level do you empirically treat for sarcoid? Do you do bronchoscopic BAL upfront?',                                                                                                              imageUrl:null, tags:['#Ophthalmology','#Uveitis','#Sarcoidosis','#TB'],              specialty:'Ophthalmology',      flair:'Case Study',          upvotes:174, downvotes:9,  comments:4, shares:21, awards:[{type:'helpful',count:3}],                                               is_pinned:false, created_at:ago(20),  updated_at:ago(20)  },
    { id:'mp-007', author:{ name:'Dr. Ananya Roy',          title:'Consultant Psychiatrist & Psychopharmacologist',    image:'https://i.pravatar.cc/150?img=44', verified:true  }, title:'Ketamine/Esketamine for Treatment-Resistant Depression — Your Clinical Experience?',                             body:'We have treated 28 TRD patients with intranasal esketamine (Spravato) over 18 months. 11/28 showed \u226550% MADRS reduction at week 4. Dissociative side effects were transient. The harder problem: durability. Most responders need maintenance dosing q2-4w indefinitely. Is anyone combining esketamine with intensive psychotherapy to prolong remission?',                                                                                                                            imageUrl:null, tags:['#Psychiatry','#Ketamine','#TRD','#Psychopharmacology'],        specialty:'Psychiatry',         flair:'Discussion',          upvotes:339, downvotes:14, comments:5, shares:68, awards:[{type:'gold',count:1},{type:'insightful',count:6}],                        is_pinned:false, created_at:ago(71),  updated_at:ago(71)  },
    { id:'mp-008', author:{ name:'Dr. Suresh Menon',        title:'Endocrinologist, Amrita Institute',                 image:'https://i.pravatar.cc/150?img=62', verified:true  }, title:'Tirzepatide in India — Who Are Your Best Responders?',                                                            body:'Mounjaro available privately since late 2025. 34 patients started with T2D + obesity. Mean %TBW loss at 6 months: 11.4% (range 4\u201318%). HbA1c reduction averaged 1.9%. Best responders: younger patients, shorter DM duration, higher baseline BMI. GI side effects led to 4 discontinuations. Anyone using it as first-line in newly diagnosed T2D+obesity?',                                                                                                                        imageUrl:null, tags:['#Endocrinology','#Tirzepatide','#T2D','#Obesity','#GLP1'],   specialty:'Endocrinology',      flair:'Clinical Experience', upvotes:295, downvotes:17, comments:4, shares:56, awards:[{type:'helpful',count:5},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(63),  updated_at:ago(63)  },
    { id:'mp-009', author:{ name:'Dr. Alan Carter',         title:'Consultant Haematologist',                          image:'https://i.pravatar.cc/150?img=52', verified:false }, title:'CAR-T Toxicity Management — CRS Grade 3 in a 67-year-old DLBCL Patient',                                        body:'Patient received axicabtagene ciloleucel for R/R DLBCL. Day 7: fever 40.2\u00B0C, hypotension requiring 3 vasopressors, ferritin 42,000, CRP 320. Grade 3 CRS. Tocilizumab 8 mg/kg \u2192 dexamethasone. Response in 36h. Questions: threshold for concurrent dexamethasone per ASTCT guidance? Siltuximab in tocilizumab-refractory CRS? CRS management in resource-limited settings?',                                                                                               imageUrl:null, tags:['#Oncology','#CART','#CRS','#Haematology','#DLBCL'],            specialty:'Oncology',           flair:'Case Study',          upvotes:201, downvotes:5,  comments:4, shares:33, awards:[{type:'helpful',count:4},{type:'gold',count:1}],                           is_pinned:false, created_at:ago(57),  updated_at:ago(57)  },
    { id:'mp-010', author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist & Critical Care, Manipal Hospital',   image:'https://i.pravatar.cc/150?img=45', verified:true  }, title:'High-Flow Nasal Cannula vs NIV in Hypoxaemic Respiratory Failure — Decision Framework',                         body:"We shifted to HFNC-first for acute hypoxaemic RF (SpO2 <90% on 15L NRB) in 2024. ROX index at 2h \u22654.88 predicts success with ~76% sensitivity. Use NIV for concurrent hypercapnia or ROX <4.88 at 2h. Intubation rate dropped 38%\u219224% over 18 months. Critical caveat: 1:2 ICU nursing is essential for safe HFNC monitoring. Sharing our decision tree — what is your institution's approach?",                                                                               imageUrl:null, tags:['#Pulmonology','#CriticalCare','#HFNC','#RespiratoryFailure'],  specialty:'Pulmonology',        flair:'Protocol',            upvotes:367, downvotes:12, comments:5, shares:74, awards:[{type:'gold',count:2},{type:'helpful',count:8},{type:'wholesome',count:1}],  is_pinned:false, created_at:ago(95),  updated_at:ago(95)  },
    { id:'mp-011', author:{ name:'Dr. Kavya Reddy',         title:"Neonatologist, Rainbow Children's Hospital",        image:'https://i.pravatar.cc/150?img=41', verified:true  }, title:'Prophylactic Indomethacin vs Conservative Management for PDA in <28-Week Preterms',                             body:'Our unit shifted from routine prophylactic indomethacin to conservative management (IVF restriction + caffeine) for haemodynamically insignificant PDA in <28 weekers in 2023. 18-month data: spontaneous closure in 71% by 36 weeks PMA. IVH rates unchanged. For haemodynamically significant PDA with pulmonary flooding we still treat — oral ibuprofen first line. Who is using catheter-based closure (Piccolo device) in <1000g?',                                                     imageUrl:null, tags:['#Neonatology','#Pediatrics','#PDA','#Prematurity'],            specialty:'Pediatrics',         flair:'Protocol',            upvotes:189, downvotes:14, comments:4, shares:30, awards:[{type:'helpful',count:4}],                                               is_pinned:false, created_at:ago(57),  updated_at:ago(57)  },
    { id:'mp-012', author:{ name:'Dr. Rohan Desai',         title:'GI & Hepatologist, Sir Ganga Ram Hospital',         image:'https://i.pravatar.cc/150?img=65', verified:true  }, title:'MASH Renaming Means More Than Semantics — New Treatment Landscape with Resmetirom',                             body:'Resmetirom (Rezdiffra) is now FDA-approved for MASH with moderate-to-advanced fibrosis — first ever approved MASH drug. Phase 3 (MAESTRO-NASH): 26% achieved MASH resolution. Who to screen (FIB-4 +/- elastography), access barriers, and long-term durability data gaps remain key challenges. In India metabolic liver disease burden is enormous but recognition lags. Are we doing enough FIB-4 screening in primary care referrals?',                                                    imageUrl:null, tags:['#Hepatology','#MASH','#NASH','#LiverDisease','#Resmetirom'],  specialty:'Gastroenterology',   flair:'Research',            upvotes:253, downvotes:8,  comments:4, shares:47, awards:[{type:'insightful',count:5},{type:'helpful',count:3}],                        is_pinned:false, created_at:ago(63),  updated_at:ago(63)  },
    { id:'mp-013', author:{ name:'Dr. Sunita Rao',          title:'Senior Cardiologist, Fortis Hospital',              image:'https://i.pravatar.cc/150?img=49', verified:true  }, title:'Echo Findings After COVID — Myocarditis or Pericarditis Spectrum?',                                              body:'28M, 6 weeks post-mild COVID, persistent palpitations and exertional dyspnoea. Echo: trivial pericardial effusion, LVEF 55%, mild diffuse wall motion abnormality. CMR: subepicardial LGE, T2 ratio elevated. Managed as myopericarditis. Questions: 1) Duration of exercise restriction — 3, 6 or 12 months? 2) Routine CMR at 6 months? 3) Anyone seeing de novo AF in younger patients post-COVID myocarditis?',                                                                         imageUrl:null, tags:['#Cardiology','#PostCOVID','#Myocarditis','#CMR'],              specialty:'Cardiology',         flair:'Case Study',          upvotes:376, downvotes:18, comments:5, shares:67, awards:[{type:'gold',count:1},{type:'insightful',count:5},{type:'helpful',count:4}],  is_pinned:false, created_at:ago(83),  updated_at:ago(83)  },
    { id:'mp-014', author:{ name:'Dr. Nisha Kapoor',        title:'Obstetrician & Maternal-Fetal Medicine',            image:'https://i.pravatar.cc/150?img=46', verified:true  }, title:'Continuous vs Intermittent EFM in Low-Risk Labour — Cochrane Evidence Revisited',                              body:'The 2023 Cochrane review (26 RCTs, >63,000 women) again confirms: cEFM increases C-section rate (RR 1.63) and instrumental delivery without reducing perinatal mortality or CP vs intermittent auscultation. Yet cEFM is de facto standard in Indian private hospitals — primarily medico-legal fear. Who has successfully shifted their unit to IA for low-risk labour? Biggest barrier — nurses, obstetricians, or administration?',                                                             imageUrl:null, tags:['#Obstetrics','#CTG','#EFM','#NormalBirth','#EBM'],             specialty:'Obstetrics',         flair:'Evidence Review',     upvotes:228, downvotes:31, comments:4, shares:51, awards:[{type:'insightful',count:4},{type:'helpful',count:2}],                        is_pinned:false, created_at:ago(40),  updated_at:ago(40)  },
    { id:'mp-015', author:{ name:'Dr. Harish Chandra',      title:'Radiologist, Tata Memorial Centre',                 image:'https://i.pravatar.cc/150?img=57', verified:true  }, title:'AI-Assisted Chest CT in Lung Cancer Screening — Practical Implementation',                                        body:'We piloted an AI nodule detection tool (Veye Lung Nodules) for 6 months. AI caught 3 subsolid nodules >6mm missed on primary read. False positive rate: 12% — higher than published specs, likely due to high TB-prevalence background. Time to report reduced 18%. The tool works best as a second pair of eyes. Regulatory pathway for AI-CAD in India remains unclear — anyone navigating CDSCO approval?',                                                                              imageUrl:null, tags:['#Radiology','#AI','#LungCancer','#CTScreening','#LDCT'],        specialty:'Radiology',          flair:'Discussion',          upvotes:219, downvotes:13, comments:4, shares:42, awards:[{type:'insightful',count:4},{type:'helpful',count:3}],                        is_pinned:false, created_at:ago(74),  updated_at:ago(74)  },
    { id:'mp-016', author:{ name:'Dr. Rahul Banerjee',      title:'Nephrology & Transplant, PGIMER Chandigarh',        image:'https://i.pravatar.cc/150?img=63', verified:true  }, title:'SGLT2 Inhibitors Post-Renal Transplant — Safety Data Update 2025',                                              body:'Four newer cohort studies confirm relative safety of SGLT2i in eGFR >30 post-renal Tx. We have started 18 patients on empagliflozin post-Tx. HbA1c improvement good; UTI incidence marginally higher (22% vs 14% historical). Critical concern: euglycaemic DKA in perioperative setting — hold 7 days pre-surgery. No significant tacrolimus level changes in our cohort. Who else is using SGLT2i post-Tx? What is your eGFR cutoff?',                                                   imageUrl:null, tags:['#Nephrology','#RenalTransplant','#SGLT2i','#Empagliflozin'],   specialty:'Nephrology',         flair:'Clinical Experience', upvotes:187, downvotes:7,  comments:4, shares:35, awards:[{type:'helpful',count:5},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(31),  updated_at:ago(31)  },
    { id:'mp-017', author:{ name:'Dr. Preeti Joshi',        title:'Emergency Medicine Consultant',                     image:'https://i.pravatar.cc/150?img=43', verified:true  }, title:'POCUS in Undifferentiated Shock — RUSH Exam Changed Diagnosis in 34% of Cases',                                 body:'Three years after adopting the RUSH protocol for all undifferentiated shock, it changed initial management in 34% of cases. Cardiac tamponade caught clinically unsuspected in 4 cases. PE vs pulmonary oedema differentiation much improved. Training curve: ~20 supervised scans for registrar competence. POCUS now embedded in resuscitation trolley workflow. What POCUS protocols are others using — BLUE? FAST+? CASA?',                                                                   imageUrl:null, tags:['#EmergencyMedicine','#POCUS','#Shock','#RUSH','#Ultrasound'],  specialty:'Emergency Medicine', flair:'Protocol',            upvotes:334, downvotes:9,  comments:5, shares:76, awards:[{type:'gold',count:1},{type:'helpful',count:7},{type:'wholesome',count:2}],  is_pinned:false, created_at:ago(111), updated_at:ago(111) },
    { id:'mp-018', author:{ name:'Dr. Karthik Anand',       title:'Plastic & Reconstructive Surgeon',                  image:'https://i.pravatar.cc/150?img=67', verified:false }, title:'3D-Printed Titanium Implants for Craniofacial Reconstruction — 2-Year Follow-up',                              body:'2-year follow-up on 12 craniofacial cases using patient-specific titanium implants (SLS manufacturing). Infection rate 1/12. Fit quality rated excellent in 10/12. Operative time saved: average 47 min per case vs conventional. Cost ~$800 higher per case. Compelling use case: complex skull base and orbital floor where off-the-shelf sizes do not fit. Anyone using PEEK 3D implants? Comparative fatigue tolerance data?',                                                            imageUrl:null, tags:['#PlasticSurgery','#3DPrinting','#Reconstruction','#Craniofacial'], specialty:'Surgery',           flair:'Research',            upvotes:162, downvotes:5,  comments:3, shares:23, awards:[{type:'insightful',count:3}],                                               is_pinned:false, created_at:ago(18),  updated_at:ago(18)  },
    { id:'mp-019', author:{ name:'Dr. Shalini Gupta',       title:'Rheumatologist, AIIMS Bhopal',                      image:'https://i.pravatar.cc/150?img=40', verified:true  }, title:'JAK Inhibitors vs Biologics in RA — Updated Risk-Benefit Framework Post ORAL Surveillance',                    body:'Post ORAL Surveillance (baricitinib/tofacitinib MACE and malignancy signals in 50+ with CV risk), my updated approach: JAKi for RA patients <50, no CV risk, non-smokers — still first choice after csDMARD failure. For >50 with any ASCVD risk \u2192 biologic preferred. Upadacitinib (selective JAK1) and filgotinib have somewhat better CV signals but class warnings persist. Thoughts?',                                                                                       imageUrl:null, tags:['#Rheumatology','#JAKinhibitors','#RA','#Biologics'],            specialty:'Rheumatology',       flair:'Clinical Experience', upvotes:276, downvotes:14, comments:4, shares:48, awards:[{type:'insightful',count:5},{type:'helpful',count:4}],                        is_pinned:false, created_at:ago(57),  updated_at:ago(57)  },
    { id:'mp-020', author:{ name:'Dr. Mohan Pillai',        title:'Dental & Maxillofacial Surgeon',                    image:'https://i.pravatar.cc/150?img=69', verified:false }, title:'MRONJ Prevention in Oncology Patients — Updated Dental Clearance Protocol',                                       body:'MRONJ remains under-recognised by oncologists. Our protocol: mandatory dental clearance 4 weeks pre-bisphosphonate initiation; all extractions completed. Drug holiday debate — oral bisphosphonates >4 years: 2-month holiday pre-implant/major surgery. Denosumab: 6-month interval approach. Key gap: oncology teams rarely refer for dental clearance at initiation. Any hospital that has solved this with a shared pathway?',                                                           imageUrl:null, tags:['#Dentistry','#MRONJ','#Bisphosphonates','#Oncology'],          specialty:'Dentistry',          flair:'Protocol',            upvotes:144, downvotes:4,  comments:3, shares:19, awards:[{type:'helpful',count:3}],                                               is_pinned:false, created_at:ago(31),  updated_at:ago(31)  },
    { id:'mp-021', author:{ name:'Dr. Divya Menon',         title:'Allergist & Clinical Immunologist',                 image:'https://i.pravatar.cc/150?img=42', verified:true  }, title:'Penicillin Allergy De-Labelling — 83% of Referrals Were Tolerant on Challenge',                                  body:'Of 320 patients referred with penicillin allergy, 83% had confirmed tolerance on graded oral challenge. Incorrect allergy labels cause broader-spectrum antibiotic use, higher C. difficile rates, longer hospital stays. Our protocol: detailed history \u2192 skin test (minor/major determinants) \u2192 oral challenge. Time per patient: 3-4 hours. We are now embedding this into pre-surgical assessment. Any institution running systematic delabelling for surgical patients?',                imageUrl:null, tags:['#Allergy','#PenicillinAllergy','#AntibioticStewardship'],      specialty:'Immunology',         flair:'Research',            upvotes:308, downvotes:11, comments:5, shares:71, awards:[{type:'gold',count:1},{type:'helpful',count:6},{type:'insightful',count:3}],  is_pinned:false, created_at:ago(83),  updated_at:ago(83)  },
    { id:'mp-022', author:{ name:'Dr. Arjun Nair',          title:'Interventional Cardiologist, AIIMS Delhi',          image:'https://i.pravatar.cc/150?img=11', verified:true  }, title:'iFR vs FFR for Intermediate Stenosis — Still Using Adenosine?',                                                   body:'iFR is now our default for angio-intermediate lesions (50-70%). Avoids adenosine side effects, faster cath lab list. DEFINE-FLAIR and iFR-SWEDEHEART trials show non-inferiority to FFR for MACE. My only holdout: ostial left main and diffuse disease — I still prefer FFR pullback. Wire-based co-registration (SyncVision/CoRoute) has been game-changing for multi-vessel PCI planning. What is the current practice at your cath labs?',                                                 imageUrl:null, tags:['#Cardiology','#PCI','#iFR','#FFR','#Coronary'],                specialty:'Cardiology',         flair:'Discussion',          upvotes:221, downvotes:12, comments:4, shares:36, awards:[{type:'insightful',count:3},{type:'helpful',count:2}],                        is_pinned:false, created_at:ago(9),   updated_at:ago(9)   },
    { id:'mp-023', author:{ name:'Dr. Pooja Agarwal',       title:'Paediatric Neurologist',                            image:'https://i.pravatar.cc/150?img=39', verified:true  }, title:'Functional Seizures vs Epilepsy — Clinical Cues That Change Management',                                         body:'PNES accounts for ~20-30% of refractory epilepsy referrals. Clinical distinguishers: eyes open during event favours epilepsy; ictal stuttering/weeping/gradual onset favours PNES; postictal confusion strongly favours epilepsy; normal EEG during event is near-diagnostic. Video-EEG is gold standard. After diagnosis: immediate AED cessation and rapid CBT referral. Who is doing video-EEG telemetry in community hospitals — feasible outside tertiary centres?',                         imageUrl:null, tags:['#Neurology','#PNES','#Epilepsy','#Paediatrics','#EEG'],      specialty:'Neurology',          flair:'Clinical Experience', upvotes:194, downvotes:8,  comments:4, shares:37, awards:[{type:'helpful',count:4},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(31),  updated_at:ago(31)  },
    { id:'mp-024', author:{ name:'Dr. Ramesh Iyer',         title:'Infectious Disease Specialist',                     image:'https://i.pravatar.cc/150?img=70', verified:true  }, title:'Ceftazidime-Avibactam for KPC-Producing Klebsiella BSI — Real-World Outcomes',                                  body:'31 patients with confirmed KPC K. pneumoniae BSI treated with CZA. 30-day mortality: 25.8%. 8/31 had concurrent meropenem (heteroresistance concern in high inoculum BSI). Resistance emergence on CZA monotherapy in 3 patients — all had inadequate source control. Critical: CZA is inactive against MBL (NDM, VIM) producers — phenotypic prediction vs genotyping essential. India NDM prevalence makes this particularly relevant.',                                                    imageUrl:null, tags:['#InfectiousDisease','#AMR','#KPC','#CZA','#Klebsiella'],      specialty:'Infectious Disease', flair:'Clinical Experience', upvotes:267, downvotes:6,  comments:4, shares:53, awards:[{type:'gold',count:1},{type:'helpful',count:5}],                           is_pinned:false, created_at:ago(63),  updated_at:ago(63)  },
    { id:'mp-025', author:{ name:'Dr. Deepa Iyer',          title:'Sports Medicine Physician',                         image:'https://i.pravatar.cc/150?img=38', verified:false }, title:'Exercise Prescription in HFpEF — How Aggressive Should We Be?',                                                   body:'HFpEF has no disease-modifying pharmacotherapy. Exercise training consistently improves VO2 peak and QoL. Our cardiac rehab programme now accepts HFpEF patients: 3x/week moderate-intensity aerobic + resistance 2x/week. 6-month data: VO2 peak +2.1 mL/kg/min, 6MWT +68m, KCCQ +14 points. AF management during exercise prescription is the main complication. Who is running cardiac rehab for HFpEF?',                                                                              imageUrl:null, tags:['#Cardiology','#HFpEF','#CardiacRehab','#ExerciseMedicine'],    specialty:'Cardiology',         flair:'Protocol',            upvotes:198, downvotes:10, comments:4, shares:34, awards:[{type:'helpful',count:4},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(57),  updated_at:ago(57)  },
    { id:'mp-026', author:{ name:'Dr. Siddharth Rao',       title:'Intensivist & Anaesthesiologist',                   image:'https://i.pravatar.cc/150?img=68', verified:true  }, title:'Lung-Protective Ventilation Beyond ARDS — Implementing Universally in ICU?',                                     body:'PReVENT trial showed low tidal volume (6 mL/kg PBW) matters even in patients WITHOUT ARDS at ICU admission. We implemented universal 6 mL/kg PBW + driving pressure <16 cmH2O for all intubated patients. Compliance: 83%. Most pushback from cardiac surgery teams. Result: new ARDS incidence 14%\u21928% in general ICU. Barotrauma rate unchanged. Any ICUs implementing driving pressure alarms vs static volume targets?',                                                        imageUrl:null, tags:['#CriticalCare','#Ventilator','#ARDS','#LungProtection','#ICU'],specialty:'Pulmonology',        flair:'Protocol',            upvotes:289, downvotes:11, comments:5, shares:58, awards:[{type:'gold',count:1},{type:'helpful',count:6}],                           is_pinned:false, created_at:ago(119), updated_at:ago(119) },
    { id:'mp-027', author:{ name:'Dr. Meenakshi Sundaram',  title:'Gynaecologic Oncologist',                           image:'https://i.pravatar.cc/150?img=37', verified:true  }, title:'PARP Inhibitors in BRCA-Wild-Type Ovarian Cancer — Who Benefits?',                                              body:'Niraparib maintenance now approved regardless of BRCA status in platinum-sensitive ovarian cancer (PRIMA). HRD subgroup benefits most (HR 0.43 vs 0.68 HRD-negative). We do BRCA1/2 germline + somatic AND myChoice HRD score for all high-grade serous OC. HRD-positive non-BRCA patients: strong niraparib indication. HRD-negative: benefit smaller but real. Cost \u20B91.8L/month without insurance — how are you navigating access?',                                                    imageUrl:null, tags:['#Oncology','#OvarianCancer','#PARP','#BRCA','#Gynaecology'],   specialty:'Oncology',           flair:'Research',            upvotes:214, downvotes:7,  comments:4, shares:41, awards:[{type:'helpful',count:4},{type:'insightful',count:3}],                        is_pinned:false, created_at:ago(83),  updated_at:ago(83)  },
    { id:'mp-028', author:{ name:'Dr. Vijay Bhat',          title:'Nuclear Medicine & PET Specialist',                 image:'https://i.pravatar.cc/150?img=66', verified:true  }, title:'PSMA PET/CT is Replacing Bone Scan in Prostate Cancer Staging — Should It?',                                     body:'68Ga-PSMA PET/CT shows superior sensitivity (PR-AUC 0.89 vs 0.23 for bone scan) for nodal and osteoblastic metastases. But PSMA is not expressed in ~10-15% of high-grade PCa — often the most aggressive. Our approach: PSA >1 post-RP \u2192 PSMA PET \u2192 if negative, consider fluciclovine or choline PET before salvage RT. Any centres offering 177Lu-PSMA in India outside trials?',                                                                                         imageUrl:null, tags:['#NuclearMedicine','#Radiology','#ProstateCancer','#PSMAPET'], specialty:'Radiology',          flair:'Discussion',          upvotes:231, downvotes:9,  comments:4, shares:45, awards:[{type:'insightful',count:4},{type:'helpful',count:3}],                        is_pinned:false, created_at:ago(95),  updated_at:ago(95)  },
    { id:'mp-029', author:{ name:'Dr. Ananya Roy',          title:'Consultant Psychiatrist & Psychopharmacologist',    image:'https://i.pravatar.cc/150?img=44', verified:true  }, title:'Clozapine Monitoring — Are We Over-Monitoring Stable Patients?',                                                   body:'2024 UK and Australian data support de-escalating haematological monitoring to 4-weekly after 12 months, and 12-weekly after 5 years. ANC monitoring yield after 18 months is extremely low (agranulocytosis incidence drops to ~0.007%/year). De-escalation saves ~1,200 unnecessary blood tests/year in our cohort of ~300. Important: metabolic monitoring (lipids, glucose, HbA1c, weight) is WHERE we are under-monitoring. Thoughts on pragmatic schedules?',                          imageUrl:null, tags:['#Psychiatry','#Clozapine','#Schizophrenia','#TreatmentResistant'], specialty:'Psychiatry',       flair:'Discussion',          upvotes:248, downvotes:19, comments:4, shares:43, awards:[{type:'helpful',count:5},{type:'insightful',count:2}],                        is_pinned:false, created_at:ago(63),  updated_at:ago(63)  },
    { id:'mp-030', author:{ name:'Dr. Kavita Sharma',       title:'Clinical Pharmacologist & Toxicologist',            image:'https://i.pravatar.cc/150?img=36', verified:true  }, title:'Medication Errors in ICU Are a Systems Problem, Not a People Problem',                                           body:'Our 6-month prospective ICU audit (n=187): 432 medication errors caught, 12 causing temporary harm, 0 permanent harm. Top types: dose errors (41%), wrong timing (28%), omission (19%), wrong route (12%). Electronic prescribing with CPOE + pharmacist review caught 78% before reaching patient. Verbal orders: single biggest risk factor (OR 6.2 for error). What system-level interventions have had the biggest impact at your ICU?',                                                   imageUrl:null, tags:['#PatientSafety','#ICU','#MedicationError','#Pharmacology','#CPOE'], specialty:'Pharmacology',   flair:'Research',            upvotes:357, downvotes:8,  comments:5, shares:87, awards:[{type:'gold',count:2},{type:'helpful',count:7},{type:'wholesome',count:2}],  is_pinned:false, created_at:ago(142), updated_at:ago(142) },
  ];

  const COMMENTS = {
    'mp-001': [
      { author:{ name:'Dr. Preeti Joshi',       title:'Emergency Medicine Consultant',          image:'https://i.pravatar.cc/150?img=43', verified:true  }, body:'SCAD is chronically under-recognised. We now have a SCAD pathway triggered when any woman <55 without traditional risk factors presents with ACS. Key: avoid thrombolytics. Dual antiplatelet for 12 months — some centres extend to 24 in recurrent SCAD or multivessel disease.', upvotes:42, downvotes:1 },
      { author:{ name:'Dr. Sunita Rao',         title:'Senior Cardiologist, Fortis Hospital',   image:'https://i.pravatar.cc/150?img=49', verified:true  }, body:'Great case. The Type 2 imaging pattern (intramural haematoma without intimal tear) is actually the most common SCAD subtype — often missed on routine angio. OCT or IVUS is game-changing for confirming the diagnosis.', upvotes:38, downvotes:0 },
      { author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist & Critical Care',         image:'https://i.pravatar.cc/150?img=45', verified:true  }, body:'Did you screen for connective tissue disease? Fibromuscular dysplasia co-exists in ~50-86% of SCAD cases. Renal artery FMD screening by CTA abdomen is our routine now.', upvotes:29, downvotes:0 },
      { author:{ name:'Dr. Deepa Iyer',         title:'Sports Medicine Physician',              image:'https://i.pravatar.cc/150?img=38', verified:false }, body:'On anti-platelet duration — the SCAD-1 pilot RCT (n=80) is underway but results not expected until 2027. Most expert consensus suggests 12 months DAPT, then aspirin indefinitely in recurrent presenters. Beta-blockers preferred over CCBs per most guidance.', upvotes:24, downvotes:0 },
      { author:{ name:'Dr. Nisha Kapoor',       title:'Obstetrician & Maternal-Fetal Medicine', image:'https://i.pravatar.cc/150?img=46', verified:true  }, body:'Important note: SCAD incidence spikes peripartum — particularly in the first few weeks postpartum. Worth flagging in obstetric units. 1 in 1,000 spontaneous SCDs in peripartum women in published series.', upvotes:31, downvotes:1 },
    ],
    'mp-003': [
      { author:{ name:'Dr. Pooja Agarwal',      title:'Paediatric Neurologist',                 image:'https://i.pravatar.cc/150?img=39', verified:true  }, body:'Plasma p-tau217 (Lumipulse or Lilly assay) is now showing AUC >0.95 for differentiating AD from non-AD dementias in research cohorts. We are running a pilot to use it as a gatekeeper before amyloid PET referral. Reduces PET cost burden significantly.', upvotes:55, downvotes:2 },
      { author:{ name:'Dr. Rajesh Kumar',       title:'Senior Neurologist, Bombay Hospital',    image:'https://i.pravatar.cc/150?img=58', verified:true  }, body:'Good discussion. For those who can access CSF, Lumipulse Abeta42/40 ratio + p-tau181 has ~90% concordance with amyloid PET in our small internal series. Cost: ~\u20B918,000 vs \u20B92.4L for PET. Worth validating locally.', upvotes:47, downvotes:0 },
      { author:{ name:'Dr. Suresh Menon',       title:'Endocrinologist, Amrita Institute',      image:'https://i.pravatar.cc/150?img=62', verified:true  }, body:'Metabolic comorbidities matter here. Insulin resistance (type 2 DM, obesity) significantly accelerates amyloid accumulation. I am increasingly convinced metabolic management is an underutilised preventive lever — GLP-1 receptor agonist trials in AD are intriguing.', upvotes:39, downvotes:1 },
      { author:{ name:'Dr. Ananya Roy',         title:'Consultant Psychiatrist',                image:'https://i.pravatar.cc/150?img=44', verified:true  }, body:'The neuropsychiatric symptom burden (anxiety, agitation, depression) in early AD is often undertreated while awaiting disease-modifying therapy access. Citalopram for agitation, mirtazapine for sleep/appetite in early MCI — do not wait for the expensive drugs to manage QoL.', upvotes:33, downvotes:0 },
      { author:{ name:'Dr. Harish Chandra',     title:'Radiologist, Tata Memorial Centre',      image:'https://i.pravatar.cc/150?img=57', verified:true  }, body:'FDG-PET brain has relatively good sensitivity for AD pattern vs frontotemporal dementia differentiation and is more accessible than amyloid PET. For resource-constrained settings, FDG-PET + clinical + structural MRI (hippocampal volumes) can be a reasonable workup.', upvotes:28, downvotes:0 },
    ],
    'mp-007': [
      { author:{ name:'Dr. Rahul Banerjee',     title:'Nephrology & Transplant, PGIMER',       image:'https://i.pravatar.cc/150?img=63', verified:true  }, body:'Combining esketamine with psychodynamic therapy in 11 patients over the last year. Anecdotally the response duration does seem longer with concurrent therapy vs drug alone — but n is too small for any conclusions. Anyone aware of an ongoing RCT?', upvotes:37, downvotes:0 },
      { author:{ name:'Dr. Shalini Gupta',      title:'Rheumatologist, AIIMS Bhopal',          image:'https://i.pravatar.cc/150?img=40', verified:true  }, body:'The REMS programme overhead is genuinely prohibitive in smaller centres. We had to designate a dedicated REMS coordinator (an overworked nurse practitioner). The 2-hour monitoring window per dose adds ~15 hours of nursing time per patient per month. A simplified monitoring pathway for long-term stable patients is needed.', upvotes:44, downvotes:1 },
      { author:{ name:'Dr. Divya Menon',        title:'Allergist & Clinical Immunologist',      image:'https://i.pravatar.cc/150?img=42', verified:true  }, body:'For patients who cannot afford esketamine, oral ketamine (off-label, compounded) has some RCT data — ELEKT-D trial (2023) showed 0.5 mg/kg sublingual 3x/week for 4 weeks: response rate ~20% better than placebo at week 4. Not regulatory-approved but manageable at home without REMS burden.', upvotes:31, downvotes:2 },
      { author:{ name:'Dr. Rohan Desai',        title:'GI & Hepatologist',                     image:'https://i.pravatar.cc/150?img=65', verified:true  }, body:'Hepatotoxicity is worth monitoring with repeated esketamine use. We check LFTs at baseline and every 3 months. One patient with pre-existing MASH had transaminase elevation — reduced frequency to monthly and LFTs normalised.', upvotes:26, downvotes:0 },
      { author:{ name:'Dr. Kavita Sharma',      title:'Clinical Pharmacologist',               image:'https://i.pravatar.cc/150?img=36', verified:true  }, body:'Drug interaction point: esketamine + MAOIs is absolutely contraindicated. Serotonin syndrome risk with concurrent strong serotonergic agents. In patients on SNRIs, watch carefully in the 2-hour observation window for tachycardia and agitation — these are early serotonin syndrome flags, not just ketamine side effects.', upvotes:41, downvotes:0 },
    ],
    'mp-010': [
      { author:{ name:'Dr. Siddharth Rao',      title:'Intensivist & Anaesthesiologist',        image:'https://i.pravatar.cc/150?img=68', verified:true  }, body:'ROX index is genuinely useful but has limitations in obese patients and those with chronic hypercapnia. We now use ROX + serial ABGs (PaO2/FiO2 ratio trend) together. A rising PaCO2 on serial ABG at 1h is our strongest trigger to escalate to NIV despite a reassuring ROX.', upvotes:48, downvotes:0 },
      { author:{ name:'Dr. Kavya Reddy',        title:"Neonatologist, Rainbow Children's Hosp", image:'https://i.pravatar.cc/150?img=41', verified:true  }, body:'Heated humidification is essential for HFNC — unhumidified high-flow causes mucosal drying and ciliary dysfunction within 4 hours, paradoxically worsening secretion clearance. Surprising how many centres are still using cold, dry HFNC.', upvotes:35, downvotes:1 },
      { author:{ name:'Dr. Preeti Joshi',       title:'Emergency Medicine Consultant',          image:'https://i.pravatar.cc/150?img=43', verified:true  }, body:'In our ED we found HFNC failed more often in patients with resting RR >34 at initiation — these patients seem to have crossed a fatigue threshold where the physiology of HFNC cannot compensate. We still try, but earlier ICU discussion for RR >34 + SpO2 <92% despite 60L HFNC.', upvotes:31, downvotes:0 },
      { author:{ name:'Dr. Ramesh Iyer',        title:'Infectious Disease Specialist',          image:'https://i.pravatar.cc/150?img=70', verified:true  }, body:'Infection control point: HFNC generates aerosol. Earlier COVID data suggested 5-fold increase in viral load dispersal vs standard oxygen. Negative-pressure rooms or at least surgical-grade ventilated isolation bays are important for suspected/confirmed infectious aetiologies.', upvotes:28, downvotes:0 },
      { author:{ name:'Dr. Meenakshi Sundaram', title:'Gynaecologic Oncologist',                image:'https://i.pravatar.cc/150?img=37', verified:true  }, body:'In our oncology HDU, immunosuppressed patients on HFNC have worse outcomes than general ICU patients with similar ROX scores. The immunosuppression masks respiratory drive — patients tolerate worsening hypoxia without perceived dyspnoea. Earlier intubation threshold in neutropenic fever on HFNC.', upvotes:22, downvotes:0 },
    ],
    'mp-013': [
      { author:{ name:'Dr. Arjun Nair',         title:'Interventional Cardiologist, AIIMS Delhi', image:'https://i.pravatar.cc/150?img=11', verified:true }, body:'For exercise restriction, the ESC 2023 guidelines recommend return to competitive sport at 3-6 months with repeat CMR showing no active inflammation (T1/T2 normalisation). Recreational exercise can resume earlier. We use a graded exercise test at 3 months — if no symptoms/arrhythmias on stress echo, allow moderate-intensity activity.', upvotes:52, downvotes:0 },
      { author:{ name:'Dr. Vikram Sinha',       title:'Consultant Orthopaedic Surgeon',          image:'https://i.pravatar.cc/150?img=60', verified:true }, body:'Not cardiology, but increasingly seeing post-COVID myocarditis clearance letters requested before sports physicals in young athletes. Worth developing a standardised return-to-sport certification pathway at your centre.', upvotes:18, downvotes:2 },
      { author:{ name:'Dr. Kavya Reddy',        title:'Neonatologist',                           image:'https://i.pravatar.cc/150?img=41', verified:true }, body:'Paediatric post-COVID myocarditis is our concern here. MIS-C overlap spectrum — we are seeing more adolescents with LGE on CMR at 6-month follow-up after initial MIS-C, even those who appeared to recover fully. Routine CMR at 6 months is our current policy for MIS-C.', upvotes:29, downvotes:0 },
      { author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist',                          image:'https://i.pravatar.cc/150?img=45', verified:true }, body:'On de novo AF: we have identified 3 cases of new-onset AF at 3-6 months post-COVID in the 30-45 age group — all had elevated inflammatory markers (CRP >10) at COVID presentation. Worth prospective tracking.', upvotes:34, downvotes:1 },
      { author:{ name:'Dr. Rahul Banerjee',     title:'Nephrology & Transplant',                 image:'https://i.pravatar.cc/150?img=63', verified:true }, body:'Colchicine 0.5 mg BD was well-tolerated in our post-COVID myopericarditis patients. Would not omit it in favour of NSAIDs alone — the anti-inflammatory mechanism is distinct and complementary. Duration: 3 months minimum.', upvotes:27, downvotes:0 },
    ],
    'mp-017': [
      { author:{ name:'Dr. Kavita Sharma',      title:'Clinical Pharmacologist',               image:'https://i.pravatar.cc/150?img=36', verified:true  }, body:'The real value of RUSH is in separating hypovolaemic from cardiogenic shock early. We had a case of apparent septic shock in hypertension — RUSH showed a grossly dilated RV with D-sign and pericardial effusion. Actual diagnosis: massive PE with obstructive shock. Beta-agonists and fluids would have been catastrophic.', upvotes:58, downvotes:0 },
      { author:{ name:'Dr. Ramesh Iyer',        title:'Infectious Disease Specialist',          image:'https://i.pravatar.cc/150?img=70', verified:true  }, body:'The BLUE (bedside lung ultrasound in emergency) protocol integrated into RUSH significantly improves respiratory component assessment. The A+B lines protocol is learnable in <3 hours. I trained our ID fellows on it after noticing ARDS vs HCAP was being confused in complex sepsis.', upvotes:42, downvotes:1 },
      { author:{ name:'Dr. Arjun Nair',         title:'Interventional Cardiologist',            image:'https://i.pravatar.cc/150?img=11', verified:true  }, body:'VTI (velocity-time integral) as a surrogate for fluid responsiveness is a valuable POCUS add-on. LVOT VTI <18 cm and variation >10% with PLR predicts fluid responsiveness with ~80% accuracy. Has essentially replaced our blind saline challenges.', upvotes:36, downvotes:0 },
      { author:{ name:'Dr. Siddharth Rao',      title:'Intensivist',                            image:'https://i.pravatar.cc/150?img=68', verified:true  }, body:'Caution: POCUS quality varies massively with practitioner experience. In our ICU, a structured competency-based sign-off system (FUSIC in the UK; iSCUS equivalents) reduced POCUS misinterpretation errors significantly. Self-proclaimed POCUS competence without formal accreditation is a real patient safety issue.', upvotes:45, downvotes:2 },
      { author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist & Critical Care',         image:'https://i.pravatar.cc/150?img=45', verified:true  }, body:'IVC collapsibility index is the most debated POCUS parameter. In spontaneously breathing patients it is more reliable for fluid status. In ventilated patients with low PEEP, use with caution — PEEP itself affects IVC morphology. We use IVC only in conjunction with other RUSH components now, not in isolation.', upvotes:39, downvotes:0 },
    ],
    'mp-021': [
      { author:{ name:'Dr. Ramesh Iyer',        title:'Infectious Disease Specialist',          image:'https://i.pravatar.cc/150?img=70', verified:true  }, body:'Strong evidence here. Every antibiotic stewardship programme should include penicillin de-labelling. The downstream effects — including reducing 3rd-generation cephalosporin and fluoroquinolone use — are directly measurable on your antibiogram within 12-18 months.', upvotes:61, downvotes:0 },
      { author:{ name:'Dr. Kavita Sharma',      title:'Clinical Pharmacologist',               image:'https://i.pravatar.cc/150?img=36', verified:true  }, body:'We piloted rapid allergy de-labelling in our pre-anaesthesia assessment clinic. Graded oral amoxicillin challenge (25mg \u2192 250mg \u2192 500mg at 30-min intervals under observation) takes 2 hours and has an excellent safety profile. 0 anaphylaxis events in 180 challenges in our series.', upvotes:52, downvotes:0 },
      { author:{ name:'Dr. Preeti Joshi',       title:'Emergency Medicine Consultant',          image:'https://i.pravatar.cc/150?img=43', verified:true  }, body:'In the ED, penicillin-labelled patients have consistently poorer outcomes for infective endocarditis (forced to use vancomycin vs amoxicillin-gentamicin), group A strep sepsis, and syphilis. The mortality signal from incorrect allergy labelling is actually quite clear in large retrospective analyses.', upvotes:44, downvotes:1 },
      { author:{ name:'Dr. Vikram Sinha',       title:'Consultant Orthopaedic Surgeon',         image:'https://i.pravatar.cc/150?img=60', verified:true  }, body:'Co-amoxiclav is vastly superior to cephalosporins for clean orthopaedic surgical prophylaxis. Our infection rates in hip arthroplasty dropped from 1.4% \u2192 0.7% when we moved allergic-labelled patients through a pre-op de-labelling pathway. The clinical value is not abstract — it is directly measurable.', upvotes:38, downvotes:0 },
      { author:{ name:'Dr. Divya Menon',        title:'Allergist & Clinical Immunologist',      image:'https://i.pravatar.cc/150?img=42', verified:true  }, body:'Important distinction: penicillin skin testing has a negative predictive value >97% in large series. The old graded-challenge-only approach can skip skin testing for low-risk patients (remote history, mild reaction, no systemic features) — this significantly reduces clinic time without compromising safety.', upvotes:33, downvotes:0 },
    ],
    'mp-026': [
      { author:{ name:'Dr. Kavya Reddy',        title:"Neonatologist, Rainbow Children's Hosp", image:'https://i.pravatar.cc/150?img=41', verified:true  }, body:'Driving pressure monitoring is critical. In our NICU, even with "standard" low tidal volumes, patients with small compliant lungs can have driving pressures >18 cmH2O leading to injurious ventilation. Closed-loop ventilation (ASV/INTELLiVENT-ASV) automatically titrates to driving pressure targets — worth evaluating.', upvotes:44, downvotes:0 },
      { author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist',                         image:'https://i.pravatar.cc/150?img=45', verified:true  }, body:'The resistance from cardiac surgery anaesthesia is real in our institution too. Their concern: low TV increases risk of atelectasis in single ventricle/post-CPB lungs with intrinsically high shunt. A middle ground — 6-8 mL/kg with PEEP titration and recruitment manoeuvre post-CPB — is our current cardiac surgical ICU protocol.', upvotes:37, downvotes:1 },
      { author:{ name:'Dr. Siddharth Rao',      title:'Intensivist',                            image:'https://i.pravatar.cc/150?img=68', verified:true  }, body:'Mechanical power (a composite of TV, rate, PEEP, driving pressure) is emerging as the most comprehensive single ventilatory injury parameter. Target <17 J/min in non-ARDS, <12 J/min in ARDS. We have added mechanical power calculation to our daily ventilator rounds.', upvotes:50, downvotes:0 },
      { author:{ name:'Dr. Ramesh Iyer',        title:'Infectious Disease Specialist',          image:'https://i.pravatar.cc/150?img=70', verified:true  }, body:'In our infectious disease-complicated respiratory failure patients (PCP pneumonia, severe influenza), I have noticed the lung mechanics change rapidly within 24-48 hours — compliance drops precipitously. Daily plateau pressure and driving pressure checks are essential, not just admission assessment.', upvotes:28, downvotes:0 },
      { author:{ name:'Dr. Preeti Joshi',       title:'Emergency Medicine Consultant',          image:'https://i.pravatar.cc/150?img=43', verified:true  }, body:'Pre-oxygenation strategy matters enormously for downstream lung-protective ventilation success. High-flow + NIV in the ED during RSI, followed by immediate 6 mL/kg PBW at intubation, dramatically reduces the "first 30 minutes" lung injury window that often comes from post-intubation full-volume breaths.', upvotes:35, downvotes:0 },
    ],
    'mp-030': [
      { author:{ name:'Dr. Siddharth Rao',      title:'Intensivist',                            image:'https://i.pravatar.cc/150?img=68', verified:true  }, body:'The single most impactful intervention in our ICU was removing verbal orders entirely for high-alert medications (insulin, heparin, vasopressors, concentrated electrolytes). Every order must be entered in CPOE. Compliance took 6 months to embed culturally but near-eliminated this category of error.', upvotes:78, downvotes:0 },
      { author:{ name:'Dr. Kavita Sharma',      title:'Clinical Pharmacologist',               image:'https://i.pravatar.cc/150?img=36', verified:true  }, body:'Smart infusion pumps with a drug library (hard and soft limits) are genuinely life-saving for ICU infusions. Our analysis: 6.2% of programmed infusion orders triggered a soft limit alert, and 0.8% triggered a hard stop. Without the pump library, those 0.8% would have reached the patient.', upvotes:62, downvotes:0 },
      { author:{ name:'Dr. Meera Krishnamurthy', title:'Pulmonologist',                         image:'https://i.pravatar.cc/150?img=45', verified:true  }, body:'Pharmacist presence at morning ICU rounds reduced medication errors by 66% in a Mayo Clinic trial. We now have a dedicated clinical pharmacist on daily ICU rounds. The cultural shift was harder than the logistics — intensivists had to genuinely accept pharmacist input as equals on the team.', upvotes:55, downvotes:1 },
      { author:{ name:'Dr. Preeti Joshi',       title:'Emergency Medicine Consultant',          image:'https://i.pravatar.cc/150?img=43', verified:true  }, body:'Night-shift fatigue is the most under-addressed systems issue. Study after study shows error rates peak between 2-6am. A no-dose-calculation approach (using pre-printed weight-based dosing charts laminated in each bay) reduced night-shift arithmetic errors in our ED by 40%.', upvotes:49, downvotes:0 },
      { author:{ name:'Dr. Ramesh Iyer',        title:'Infectious Disease Specialist',          image:'https://i.pravatar.cc/150?img=70', verified:true  }, body:'Antibiotic dosing errors in ICU are particularly dangerous. Renally adjusted antibiotic dosing is wrong in ~30% of prescriptions in published audits when done without pharmacist input. We use AUC-guided vancomycin dosing (not trough alone) with pharmacokinetic software — eliminated vancomycin toxicity in our unit.', upvotes:41, downvotes:0 },
    ],
  };

  medicosPosts.insertMany(POSTS);

  const commentNow = new Date();
  let commentCount = 0;
  for (const [postId, cmts] of Object.entries(COMMENTS)) {
    cmts.forEach((c, i) => {
      medicosComments.insert({
        id: `mc-${postId}-${i+1}`,
        postId,
        author: c.author,
        body: c.body,
        upvotes: c.upvotes,
        downvotes: c.downvotes,
        created_at: new Date(commentNow.getTime() - (cmts.length - i) * 1800000).toISOString(),
        updated_at: new Date(commentNow.getTime() - (cmts.length - i) * 1800000).toISOString(),
      });
      commentCount++;
    });
  }

  fs.writeFileSync(_seedMeta, SEED_VERSION, 'utf8');
  console.log(`[medicos] Seeded ${POSTS.length} posts and ${commentCount} comments (${SEED_VERSION})`);
}

// ── Exported API ──────────────────────────────────────────────────────────────
module.exports = {
  insertVital: (row) => vitals.insert(row),
  getVitals: (limit=100, offset=0) => vitals.find({}, { sort:'recorded_at', order:'desc', limit, offset }),
  getVitalsRange: (from, to, limit=500) => vitals.find({ recorded_at: { _gte: from, _lte: to } }, { sort:'recorded_at', order:'desc', limit }),
  getLatestVital: () => vitals.find({}, { sort:'recorded_at', order:'desc', limit:1 })[0] ?? null,
  countVitals: () => vitals.count(),

  insertInsight: (row) => insights.insert(row),
  getInsights: (limit=20, offset=0) => insights.find({}, { sort:'created_at', order:'desc', limit, offset }),
  getLatestInsight: () => insights.find({}, { sort:'created_at', order:'desc', limit:1 })[0] ?? null,
  countInsights: () => insights.count(),

  insertAlert: (row) => alerts.insert(row),
  getActiveAlerts: (limit=50) => alerts.find({ dismissed: false }, { sort:'created_at', order:'desc', limit }),
  getAllAlerts: (limit=100, offset=0) => alerts.find({}, { sort:'created_at', order:'desc', limit, offset }),
  dismissAlert: (id) => alerts.updateOne({ id }, { dismissed: true }),
  dismissAllAlerts: () => alerts.updateMany({ dismissed: false }, { dismissed: true }),
  countActiveAlerts: () => alerts.count({ dismissed: false }),

  getProfile: () => profileColl.findOne({ id: 'default' }),
  updateProfile: (patch) => profileColl.updateOne({ id: 'default' }, { ...patch, updated_at: new Date().toISOString() }),

  insertIngestion: (row) => ingestion.insert(row),
  getIngestions: (limit=50, offset=0) => ingestion.find({}, { sort:'recorded_at', order:'desc', limit, offset }),

  insertEvent: (row) => events.insert(row),
  getEvents: (limit=50, offset=0, type=null) => events.find(type ? { type } : {}, { sort:'recorded_at', order:'desc', limit, offset }),
  countEvents: (type=null) => events.count(type ? { type } : {}),

  // ── Medicos Posts
  insertMedicosPost:  (row) => medicosPosts.insert(row),
  getMedicosPosts:    (limit = 50, offset = 0) => medicosPosts.find({}, { sort: 'created_at', order: 'desc', limit, offset }),
  getMedicosPost:     (id) => medicosPosts.findOne({ id }),
  updateMedicosPost:  (id, patch) => medicosPosts.updateOne({ id }, { ...patch, updated_at: new Date().toISOString() }),
  deleteMedicosPost:  (id) => medicosPosts.remove({ id }),
  countMedicosPosts:  () => medicosPosts.count(),

  // ── Medicos Comments
  insertMedicosComment:   (row) => medicosComments.insert(row),
  getMedicosComments:     (postId, limit = 50, offset = 0) => medicosComments.find({ postId }, { sort: 'created_at', order: 'asc', limit, offset }),
  getMedicosCommentById:  (id) => medicosComments.findOne({ id }),
  updateMedicosComment:   (id, patch) => medicosComments.updateOne({ id }, { ...patch, updated_at: new Date().toISOString() }),
  countMedicosComments:   (postId) => medicosComments.count({ postId }),

  getVitalsStats: (from) => {
    const rows = vitals.find({ recorded_at: { _gte: from } }, { limit: Number.MAX_SAFE_INTEGER });
    if (!rows.length) return null;
    const avg = arr => +(arr.reduce((a,b)=>a+b,0)/arr.length).toFixed(1);
    const hrs=rows.map(r=>r.heart_rate), sys=rows.map(r=>r.systolic_bp), dia=rows.map(r=>r.diastolic_bp), rsp=rows.map(r=>r.resp_rate), tmp=rows.map(r=>r.temperature), spo=rows.map(r=>r.oxygen_sat);
    return { avg_heart_rate:avg(hrs), max_heart_rate:Math.max(...hrs), min_heart_rate:Math.min(...hrs), avg_systolic_bp:avg(sys), avg_diastolic_bp:avg(dia), avg_resp_rate:avg(rsp), avg_temperature:+(tmp.reduce((a,b)=>a+b,0)/tmp.length).toFixed(2), avg_oxygen_sat:avg(spo), min_oxygen_sat:Math.min(...spo), total_readings:rows.length };
  },
  getCriticalAlertCount: (from) => alerts.count({ type:'warning', created_at: { _gte: from } }),
};
